### PR TITLE
WIP: Fix bootstrap nans

### LINKED ISSUE #54: nan values from StatCalculate::StdDevOfMeanFromBootstrapVariance
Hi!

In the condition of the real analysis it may happen so one or few means from bootstrap get `nan`.

In this case the `nan`-ish bootstrap mean will be propagated to all derivative objects i.e results of arithmetical operations, merges et cetera.

The most annoying thing is that even a single `nan` in the vector of bootstrap means ruins statistical error of the bin. 

It happens in the `StatCalclulate::VarianceOfMeanFromBootstrap`:
https://github.com/HeavyIonAnalysis/QnTools/blob/1f01146062d5e384821b5f292cc0f73fa104baef/include/base/QnTools/StatCalculate.hpp#L76

I don't know when and where to filter out `nan`s and who shall take care of it (keep in mind that user has no access to b-p samples). But I think it make sense to introduce guard to the `StatCalclulate::VarianceOfMeanFromBootstrap`. We can lose few samples per bin, but number of samples is usually a large number (for me it's 50), so I guess we can survive this.

### PR DESCRIPTION
**Pull request by eugene274**

### CODE REVIEW

**Comment by kreisl** [comment]
Couldn't we also handle it while constructing the StatsCalculate? We remove the nan sample means and set their weight to 0. Then we only need a special case for the division operation which sets the mean and weight to 0, if a division by zero is detected. With this we dont have to handle nans in most of the operations. 
But I dont now which way is better. If you have good reasons to do it like this I would suggest we go ahead and merge.

**Review by kreisl — COMMENTED** [review]
see previous comment.

**Comment by eugene274** [comment]
Two things concern me:

1. I'd avoid usage of `nan`-s since the behavior of `std::isnan` could be incorrect of -fast-math optimizations are used.
2. Should we notify user if `nan` has non-zero weight (e.g. Sqrt of negative argument)? I put there few asserts if nan with w > 0 appears, but this is not good. The solution could be to make global flag which defines what to do if weighted nan is produced: die with message or just ignore and forcefully set weight to 0.

**Comment by kreisl** [comment]
﻿
I agree. Asserts at the right places can help with testing. However they are not so useful for the release library.
I think a message that something failed with bootstrapping is very useful. For a default behavior I would suggest to ignore one sample and continue. 

For bootstrapping we definitely need easier access to the distribution of samples and to control plots. I have noticed myself some discussions weather the bootstrapping works in a specific case or not.
We should make a compilation of useful plots.

**Pull request merged**
